export interface Product {
  id: string
  name: string
  description: string
  price: number
  originalPrice?: number
  image: string
  category: string
  rating: number
  reviews: number
  discount?: number
  inStock: boolean
}

const products: Product[] = [
  // Groceries
  {
    id: "1",
    name: "Basmati Rice (1kg)",
    description: "Premium quality basmati rice",
    price: 250,
    originalPrice: 300,
    image: "/basmati-rice-1kg.jpg",
    category: "groceries",
    rating: 4.5,
    reviews: 128,
    discount: 17,
    inStock: true,
  },
  {
    id: "2",
    name: "Organic Millets Mix (500g)",
    description: "Healthy organic millets blend",
    price: 180,
    originalPrice: 220,
    image: "/organic-millets-mix.jpg",
    category: "groceries",
    rating: 4.3,
    reviews: 95,
    discount: 18,
    inStock: true,
  },
  {
    id: "3",
    name: "Refined Sunflower Oil (1L)",
    description: "Pure refined sunflower oil",
    price: 150,
    originalPrice: 180,
    image: "/sunflower-oil-bottle.jpg",
    category: "groceries",
    rating: 4.4,
    reviews: 156,
    discount: 17,
    inStock: true,
  },
  {
    id: "4",
    name: "Whole Wheat Flour (2kg)",
    description: "Fresh whole wheat flour",
    price: 120,
    originalPrice: 150,
    image: "/wheat-flour-bag.png",
    category: "groceries",
    rating: 4.2,
    reviews: 87,
    discount: 20,
    inStock: true,
  },

  // Kitchen Items
  {
    id: "5",
    name: "Non-Stick Frying Pan (10 inch)",
    description: "Durable non-stick cookware",
    price: 450,
    originalPrice: 600,
    image: "/non-stick-frying-pan.jpg",
    category: "kitchen",
    rating: 4.6,
    reviews: 234,
    discount: 25,
    inStock: true,
  },
  {
    id: "6",
    name: "Stainless Steel Pressure Cooker (5L)",
    description: "Heavy-duty pressure cooker",
    price: 1200,
    originalPrice: 1500,
    image: "/pressure-cooker-stainless-steel.jpg",
    category: "kitchen",
    rating: 4.7,
    reviews: 312,
    discount: 20,
    inStock: true,
  },
  {
    id: "7",
    name: "Mixing Bowls Set (3 pieces)",
    description: "Stainless steel mixing bowls",
    price: 280,
    originalPrice: 350,
    image: "/mixing-bowls-stainless-steel-set.jpg",
    category: "kitchen",
    rating: 4.4,
    reviews: 156,
    discount: 20,
    inStock: true,
  },
  {
    id: "8",
    name: "Kitchen Knife Set (6 pieces)",
    description: "Professional kitchen knives",
    price: 650,
    originalPrice: 850,
    image: "/kitchen-knife-set-professional.jpg",
    category: "kitchen",
    rating: 4.5,
    reviews: 198,
    discount: 24,
    inStock: true,
  },

  // Household Accessories
  {
    id: "9",
    name: "Microfiber Cleaning Cloth (5 pack)",
    description: "Reusable microfiber cloths",
    price: 120,
    originalPrice: 150,
    image: "/microfiber-cleaning-cloth-pack.jpg",
    category: "household",
    rating: 4.3,
    reviews: 89,
    discount: 20,
    inStock: true,
  },
  {
    id: "10",
    name: "Plastic Storage Containers (10 pieces)",
    description: "Airtight storage containers",
    price: 350,
    originalPrice: 450,
    image: "/products/storage-containers.jpg",
    category: "household",
    rating: 4.4,
    reviews: 167,
    discount: 22,
    inStock: true,
  },
  {
    id: "11",
    name: "Mop and Bucket Set",
    description: "Complete cleaning set",
    price: 280,
    originalPrice: 350,
    image: "/mop-bucket-cleaning-set.jpg",
    category: "household",
    rating: 4.2,
    reviews: 112,
    discount: 20,
    inStock: true,
  },
  {
    id: "12",
    name: "Trash Bin with Lid (20L)",
    description: "Durable waste bin",
    price: 180,
    originalPrice: 220,
    image: "/trash-bin-with-lid.jpg",
    category: "household",
    rating: 4.1,
    reviews: 76,
    discount: 18,
    inStock: true,
  },

  // Steel Items
  {
    id: "13",
    name: "Stainless Steel Utensil Set (24 pieces)",
    description: "Complete utensil collection",
    price: 1500,
    originalPrice: 2000,
    image: "/stainless-steel-utensil-set.jpg",
    category: "steel",
    rating: 4.6,
    reviews: 289,
    discount: 25,
    inStock: true,
  },
  {
    id: "14",
    name: "Steel Water Bottle (1L)",
    description: "Insulated steel bottle",
    price: 350,
    originalPrice: 450,
    image: "/steel-water-bottle-insulated.jpg",
    category: "steel",
    rating: 4.5,
    reviews: 201,
    discount: 22,
    inStock: true,
  },
  {
    id: "15",
    name: "Steel Lunch Box (3 compartments)",
    description: "Durable lunch container",
    price: 420,
    originalPrice: 550,
    image: "https://images.unsplash.com/photo-1567005211120-efb5f95f0ab2?q=80&w=1200&auto=format&fit=crop",
    category: "steel",
    rating: 4.4,
    reviews: 145,
    discount: 24,
    inStock: true,
  },
  {
    id: "16",
    name: "Steel Tiffin Set (4 pieces)",
    description: "Traditional steel tiffin",
    price: 380,
    originalPrice: 480,
    image: "https://images.unsplash.com/photo-1604335399105-43f63a5c5db3?q=80&w=1200&auto=format&fit=crop",
    category: "steel",
    rating: 4.3,
    reviews: 134,
    discount: 21,
    inStock: true,
  },

  // Snacks
  {
    id: "17",
    name: "Mixed Dry Fruits (500g)",
    description: "Premium dry fruits mix",
    price: 450,
    originalPrice: 600,
    image: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?q=80&w=1200&auto=format&fit=crop",
    category: "snacks",
    rating: 4.6,
    reviews: 267,
    discount: 25,
    inStock: true,
  },
  {
    id: "18",
    name: "Roasted Chickpeas (200g)",
    description: "Healthy roasted snack",
    price: 120,
    originalPrice: 150,
    image: "https://images.unsplash.com/photo-1590080876363-5c98d1da3f6f?q=80&w=1200&auto=format&fit=crop",
    category: "snacks",
    rating: 4.3,
    reviews: 98,
    discount: 20,
    inStock: true,
  },
  {
    id: "19",
    name: "Organic Granola (400g)",
    description: "Healthy breakfast granola",
    price: 280,
    originalPrice: 350,
    image: "https://images.unsplash.com/photo-1505577058444-a3dab90d4253?q=80&w=1200&auto=format&fit=crop",
    category: "snacks",
    rating: 4.4,
    reviews: 156,
    discount: 20,
    inStock: true,
  },
  {
    id: "20",
    name: "Cashew Nuts (250g)",
    description: "Premium cashew nuts",
    price: 380,
    originalPrice: 500,
    image: "https://images.unsplash.com/photo-1604908554027-4312922c9c81?q=80&w=1200&auto=format&fit=crop",
    category: "snacks",
    rating: 4.5,
    reviews: 189,
    discount: 24,
    inStock: true,
  },

  // Dinnersets
  {
    id: "21",
    name: "Ceramic Dinner Set (12 pieces)",
    description: "Beautiful ceramic dinnerware",
    price: 1200,
    originalPrice: 1600,
    image: "https://images.unsplash.com/photo-1604335399105-d9d4e1b1f009?q=80&w=1200&auto=format&fit=crop",
    category: "dinnersets",
    rating: 4.6,
    reviews: 234,
    discount: 25,
    inStock: true,
  },
  {
    id: "22",
    name: "Glass Dinner Set (6 pieces)",
    description: "Elegant glass dinnerware",
    price: 850,
    originalPrice: 1100,
    image: "https://images.unsplash.com/photo-1616594039964-e7152d37f4e3?q=80&w=1200&auto=format&fit=crop",
    category: "dinnersets",
    rating: 4.4,
    reviews: 167,
    discount: 23,
    inStock: true,
  },
  {
    id: "23",
    name: "Melamine Dinner Set (24 pieces)",
    description: "Durable melamine set",
    price: 650,
    originalPrice: 850,
    image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?q=80&w=1200&auto=format&fit=crop",
    category: "dinnersets",
    rating: 4.3,
    reviews: 145,
    discount: 24,
    inStock: true,
  },
  {
    id: "24",
    name: "Stoneware Dinner Set (8 pieces)",
    description: "Premium stoneware collection",
    price: 1400,
    originalPrice: 1800,
    image: "https://images.unsplash.com/photo-1541976076758-347942db1970?q=80&w=1200&auto=format&fit=crop",
    category: "dinnersets",
    rating: 4.5,
    reviews: 198,
    discount: 22,
    inStock: true,
  },
]

export function getProducts(): Product[] {
  return products
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return products.filter(
    (p) => p.name.toLowerCase().includes(lowerQuery) || p.description.toLowerCase().includes(lowerQuery),
  )
}
